import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/src/layout/Sidebar";

export const metadata = {
  title: "Satu Teladan Admin Dashboard",
  description: "Generated by Satu Teladan Admin Dashboard",
};

export default function RootLayout({ children }) {
  return (
    <html lang="id">
      <body className={`antialiased`}>
        <SidebarProvider>
          <AppSidebar />
          <main>
            <SidebarTrigger />
            {children}
          </main>
        </SidebarProvider>
        <Toaster />
      </body>
    </html>
  );
}
